//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestGuide
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Address = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int Chef = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int ChefLabel = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int CreditCards = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int CreditCardsLabel = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int Cuisine = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int Description = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int Hours = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int HoursLabel = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int List = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int Telephone = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int Title = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int Website = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int scroller = 2131099651;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Restaurant = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int restaurants = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			private String()
			{
			}
		}
	}
}
